# Generated by Django 3.2.9 on 2021-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorlog_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='max_allowed_visits',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of allowed visits.', null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='number_of_visits',
            field=models.PositiveIntegerField(default=0, help_text='Number of visits user has already made. Tracked if max visits is set.'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visits_exceeded',
            field=models.BooleanField(default=False, help_text='Set to True when max allowed visits are used up.'),
        ),
    ]
